### ISSUE TITLE
FileNotFoundError, Broken dataset assumption

### ISSUE THREAD

**Issue by JaehongJaehongMin** [mlzxy/arp#1]
Hi,
Thank you for the kind explanation of how to reproduce your code.

Unfortunately, I've encountered some exceptions during the reproducing.
I think I should prerpocess the Peract dataset before the inference.
I've followed your instruction carefully, and don't have any version issue.

But the problem is 'eval.py' code in RLBench couldn't find the test directories are not included in your box folder.
![Screenshot 2024-10-15 133928](https://github.com/user-attachments/assets/3df96e7b-ef76-4937-92ae-9101ee28687e)

To resolve this I've changed the name of the all_variations folder to variation-1, but had another issue with the pkl file.
![image](https://github.com/user-attachments/assets/86f83b28-3106-4d01-92df-2c373147f361)
The lenght of the pkl file is 429 just like the original Peract dataset, but the length of the l_sh_rgb_f (and so on) is 13 as you simplified.

Could you please share your dataset preprocessing code or explain how the handle this error?

**Comment by mlzxy** [comment]
I think I know the reason. I commented on the length check in RLBench to bypass this. This length check is unnecessary. 

Could you do it just for the moment? I can think of a better way to handle this in the mean time.

**Comment by mlzxy** [comment]
Specifically, comment out this check at https://github.com/stepjam/RLBench/blob/b80e51feb3694d9959cb8c0408cd385001b01382/rlbench/utils.py#L94

**Comment by JaehongJaehongMin** [comment]
Thank you for the quick response!
I commented out the part of the leanght check.

But I don't think that the filename error have been resolved.
![image](https://github.com/user-attachments/assets/b032891f-3962-4e72-bf7a-ceccdd286dfc)

I already restored the file name in original state.
![image](https://github.com/user-attachments/assets/48348143-a61c-4cbf-bfa7-20df7fcc2af6)

**Comment by mlzxy** [comment]
Thanks for your feedback. I am looking into it.

**Comment by mlzxy** [comment]
Hi @JaehongJaehongMin , I have fixed the issue. There are two things you need to do: 

1) Reinstall RLBench from https://github.com/mlzxy/RLBench.arp 
2) Remove line "from mvt.utils import ForkedPdb" from `point_renderer/rvt_renderer.py`

I just realized the most frequently used RLBench (with rich language variants) comes from PerAct. This fork already becomes incompatible with the master branch of RLBench. So I rebase my change (that comment line) on top of their version. 

2. The second point is not relevant to this issue, just one thing that I missed. 

Sorry for the inconvenience. I have already updated the [ENV.md](../blob/main/ENV.md) to include this. Let me know if you have any problems.
