### ISSUE TITLE
Training cost

### ISSUE THREAD

**Issue by FinnJob** [mlzxy/arp#2]
Thank you for your excellent work!
I would like to ask how much training time is required for simulation and real-world experiments, and what type of GPU is used. Thank you!

**Comment by mlzxy** [comment]
Hi @FinnJob 

For PushT, 3GB GPU memory will do. For ALOHA, 12 GB will do, such as A4000, or at most 14GB such as A4500. 

For RLBench and real world experiment, the memory costs more, I use 2xA6000 (48GB), but this can be reduced greatly by a much smaller batch size.

**Comment by mlzxy** [comment]
@FinnJob. It depends on what type of GPU you use.  If you use A6000, the rlbench training takes 24 hours, the ALOHA takes less than 4 hours, the PushT less than 8 hours.

**Comment by FinnJob** [comment]
@mlzxy Thanks!
