### ISSUE TITLE
RLBench Dataset Loading Issue

### ISSUE THREAD

**Issue by GravMAD** [mlzxy/arp#3]
Thank you for your excellent work!

I am trying to reproduce the model training. However, I encountered a problem when loading the dataset. When I run the command `python3 dataset.py` in the `rlb` directory, I get the following error:

![image](https://github.com/user-attachments/assets/9533764c-a62a-4e8f-9946-d862d6144c3f)

I downloaded the dataset from the link you provided. In the `open_drawer` episode77, the `front_rgb` folder only contains these images:

![image](https://github.com/user-attachments/assets/cc6d3d8c-fb34-4efd-9674-453cc712d35d)

This issue also prevents me from loading the dataset when running the training code, and the progress bar remains stuck at 0.

I look forward to your reply. Thank you!

**Comment by mlzxy** [comment]
Could you set  `k2k_sample_ratios` to be the following dictionary (as in the [configuration](https://github.com/mlzxy/arp/blob/main/rlb/configs/arp.yaml))? This will tell the dataset class to only load key frames.  I will change the dataset.py as well. 

```python
{
  "place_cups": 1,
  "stack_cups": 1,
  "close_jar": 1,
  "push_buttons": 1,
  "meat_off_grill": 1,
  "stack_blocks": 1,
  "reach_and_drag": 1,
  "slide_block_to_color_target": 1,
  "place_shape_in_shape_sorter": 1,
  "open_drawer": 1,
  "sweep_to_dustpan_of_size": 1,
  "put_groceries_in_cupboard": 1,
  "light_bulb_in": 1,
  "turn_tap": 1,
  "insert_onto_square_peg": 1,
  "put_item_in_drawer": 1,
  "put_money_in_safe": 1,
  "place_wine_at_rack_location": 1
}
```
