### ISSUE TITLE
difference between mvt_cameras and   cameras 

### ISSUE THREAD

**Issue by rebecajohn** [mlzxy/arp#4]
in arp.yaml , why are there two     mvt_cameras: ['top', 'left', 'front'] ,   cameras: ["front", "left_shoulder", "right_shoulder", "wrist"]  ?

**Comment by rebecajohn** [comment]
Does that mean   mvt_cameras is not for RLBench ?

**Comment by mlzxy** [comment]
The `cameras` means the cameras in the RLBench environment.  RLBench environment has five cameras: "front", "left_shoulder", "right_shoulder", "wrist", and "top". The common practice is to use the first four. You can check these cameras by opening [task_design.ttt](https://github.com/mlzxy/RLBench.arp/blob/master/rlbench/task_design.ttt) in  CoppeliaSim. 

The `mvt_cameras` denotes the virtual cameras, which are used to reproject the point cloud into new viewpoints as [here](https://github.com/mlzxy/arp/blob/1de00688c4f126849f2b66f5f5db0bc7e104f822/rlb/preprocess.py#L330). This practice is proposed in RVT paper in their multi-view transformer network, which we used as the backbone. So technically it is not just for RLBench. 

Hope this clarifies things a bit.

**Comment by rebecajohn** [comment]
Did RVT use only these ['top', 'left', 'front'] , or something else ?

**Comment by mlzxy** [comment]
You can check these in the configurations we provided for official RVT-1/2, as in [Experiment.md](https://github.com/mlzxy/arp/blob/1de00688c4f126849f2b66f5f5db0bc7e104f822/Experiments.md#baselines). 

RVT-2 uses the same. RVT-1 uses more cameras.
