### ISSUE TITLE
How to use Xvfb

### ISSUE THREAD

**Issue by hanyangclarence** [mlzxy/arp#5]
Hi, thanks for your great work!

I am also working on a headless linux server with no sudo. I tried your guidelines on using Xvfb. But after I run the command, it just got stuck:

![image](https://github.com/user-attachments/assets/00b56a12-400f-4b4d-b417-388eabde2d03)

Do you have any idea?

**Comment by mlzxy** [comment]
By default this command does not produce any output. So I believe your xvfb session is already up. 

To test this, open a new terminal in the same server, then run 

```
export DISPLAY=:99
xdpyinfo -display $DISPLAY
```

If it has output like 

```
name of display:    :99
version number:    11.0
vendor string:    CentOS
vendor release number:    11704000
maximum request size:  16777212 bytes
motion buffer size:  256
bitmap unit, bit order, padding:    32, LSBFirst, 32
image byte order:    LSBFirst
number of supported pixmap formats:    6
...
```

Then your xvfb is already running. You can run evaluation as long as the `DISPLAY` env var is set. Note that you still cannot see the visuals with xvfb (unless you turn on the video recording of the eval script by `eval.save_video=True`). If you have a Linux desktop (even with a lower-grade GPU ), you can install the environment there and run non-headless evaluation. This sometimes helps you debug faster.

**Comment by hanyangclarence** [comment]
Thanks for your comment! I have figured out how to run the code on headless device. Using `xvfb-run python eval.py xxxx` works for me.
