### ISSUE TITLE
The question about the experimental setting on the RLBench dataset.

### ISSUE THREAD

**Issue by WangJiuniu** [mlzxy/arp#6]
Thank you for this great work. The ARP model really helps me a lot.

I have a question about the experimental setting on the RLBench dataset. There is a sentence in Section 4.1 of this paper saying, "Note that the originally reported success rate of RVT-2 was 81.6%. This was achieved by using a logical time-step as an input. ... Thus, our RLBench models are more robust to variations of task initialization in real applications." While I find that the time-step in RVT-2 was always set as 1 (see https://github.com/NVlabs/RVT/blob/master/rvt/utils/get_dataset.py#L44), and the time-step seems not to be used during training and inference in RVT-2.

Could you please help me to address this question?

Thank you very much.

**Comment by mlzxy** [comment]
Hi @WangJiuniu 

The code you referred to is the initialization of the replay buffer. The actual data are inserted with the function [fill_replay](https://github.com/NVlabs/RVT/blob/ff1065e2a5489d0fa7d99d945e0965fe620e6569/rvt/utils/dataset.py#L327). If you dive a little deeper in the codebase, you will find the timestep creation at [extract_obs](https://github.com/NVlabs/RVT/blob/ff1065e2a5489d0fa7d99d945e0965fe620e6569/rvt/utils/dataset.py#L265). 

The same timestep can be found during evaluation. We provided the timestep as in [env.py](https://github.com/mlzxy/arp/blob/1de00688c4f126849f2b66f5f5db0bc7e104f822/rlb/utils/env.py#L395). In doing so, we can reproduce exactly the metrics on the official released pretrained models of RVT1/2, as in [Experiment.md](https://github.com/mlzxy/arp/blob/main/Experiments.md#baselines).

**Comment by WangJiuniu** [comment]
Hi @mlzxy 

Thank you very much! I will dive into these codes. 

Your response has addressed my question.  Thank you!
